# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88b4789e5a65b92377ac3413c07d169300d00b4eab548ca8c55be1452cf4e3637945b445e0da842dff09a4cebe68f0d84f344667e3e019b4c874d08cf2757618

test:
  secret_key_base: 9e7a836ef2b6fcb8916ad334c89a6d4e228d0a32c2d3eb3120c49b968cb763e1acab8ba83091430b6f3f5afee6284bf519d072061bda87696ba93f7be606b247

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
